"""Справочник кодов SNMP-алертов (RFC 3805 / IANA-PRINTER-MIB) + схема alerts.db.

Вынесен в config/, чтобы не раздувать app.py: здесь только данные.
"""

# Коды prtAlertCode по RFC 3805 / IANA-PRINTER-MIB (vendor='*') + поправки
# вендоров. (vendor, code, name, title_ru, hint_ru)
ALERT_CODES_SEED = [
    # --- общие коды (1-38) ---
    ('*', 1, 'other', 'Прочее событие', None),
    ('*', 2, 'unknown', 'Неизвестное событие', None),
    ('*', 3, 'coverOpen', 'Крышка открыта', 'Закрыть крышку'),
    ('*', 4, 'coverClosed', 'Крышка закрыта', None),
    ('*', 5, 'interlockOpen', 'Блокировка открыта', None),
    ('*', 6, 'interlockClosed', 'Блокировка закрыта', None),
    ('*', 7, 'configurationChange', 'Изменение конфигурации', None),
    ('*', 8, 'jam', 'Замятие бумаги', 'Устранить замятие'),
    ('*', 9, 'subunitMissing', 'Узел снят', 'Установить узел на место'),
    ('*', 10, 'subunitLifeAlmostOver', 'Ресурс узла на исходе', None),
    ('*', 11, 'subunitLifeOver', 'Ресурс узла исчерпан', 'Заменить узел'),
    ('*', 12, 'subunitAlmostEmpty', 'Узел почти пуст', None),
    ('*', 13, 'subunitEmpty', 'Узел пуст', None),
    ('*', 14, 'subunitAlmostFull', 'Узел почти полон', None),
    ('*', 15, 'subunitFull', 'Узел полон', None),
    ('*', 16, 'subunitNearLimit', 'Узел у предела', None),
    ('*', 17, 'subunitAtLimit', 'Узел на пределе', None),
    ('*', 18, 'subunitOpened', 'Узел открыт', None),
    ('*', 19, 'subunitClosed', 'Узел закрыт', None),
    ('*', 20, 'subunitTurnedOn', 'Узел включён', None),
    ('*', 21, 'subunitTurnedOff', 'Узел выключен', None),
    ('*', 22, 'subunitOffline', 'Узел офлайн', None),
    ('*', 23, 'subunitPowerSaver', 'Спящий режим', None),
    ('*', 24, 'subunitWarmingUp', 'Прогрев', None),
    ('*', 25, 'subunitAdded', 'Узел добавлен', None),
    ('*', 26, 'subunitRemoved', 'Узел извлечён', None),
    ('*', 27, 'subunitResourceAdded', 'Ресурс добавлен', None),
    ('*', 28, 'subunitResourceRemoved', 'Ресурс извлечён', None),
    ('*', 29, 'subunitRecoverableFailure', 'Устранимый сбой узла', None),
    ('*', 30, 'subunitUnrecoverableFailure', 'Неустранимый сбой узла', 'Требуется вмешательство'),
    ('*', 31, 'subunitRecoverableStorageError', 'Устранимая ошибка памяти', None),
    ('*', 32, 'subunitUnrecoverableStorageError', 'Неустранимая ошибка памяти', None),
    ('*', 33, 'subunitMotorFailure', 'Отказ двигателя', None),
    ('*', 34, 'subunitMemoryExhausted', 'Память исчерпана', None),
    ('*', 35, 'subunitUnderTemperature', 'Недогрев', None),
    ('*', 36, 'subunitOverTemperature', 'Перегрев', None),
    ('*', 37, 'subunitTimingFailure', 'Сбой синхронизации', None),
    ('*', 38, 'subunitThermistorFailure', 'Отказ термистора', None),
    # --- общая группа принтера (501-507) ---
    ('*', 501, 'doorOpen', 'Дверца открыта', 'Закрыть дверцу'),
    ('*', 502, 'doorClosed', 'Дверца закрыта', None),
    ('*', 503, 'powerUp', 'Включение питания', None),
    ('*', 504, 'powerDown', 'Выключение питания', None),
    ('*', 505, 'printerNMSReset', 'Сброс по сети (NMS)', None),
    ('*', 506, 'printerManualReset', 'Ручной сброс', None),
    ('*', 507, 'printerReadyToPrint', 'Готов к печати', None),
    # --- лотки/подача (801-820) ---
    ('*', 801, 'inputMediaTrayMissing', 'Лоток отсутствует', 'Установить лоток'),
    ('*', 802, 'inputMediaSizeChange', 'Изменён размер бумаги', None),
    ('*', 803, 'inputMediaWeightChange', 'Изменена плотность бумаги', None),
    ('*', 804, 'inputMediaTypeChange', 'Изменён тип бумаги', None),
    ('*', 805, 'inputMediaColorChange', 'Изменён цвет бумаги', None),
    ('*', 806, 'inputMediaFormPartsChange', 'Изменён состав формы', None),
    ('*', 807, 'inputMediaSupplyLow', 'Бумага заканчивается', 'Добавить бумагу'),
    ('*', 808, 'inputMediaSupplyEmpty', 'Лоток пуст (нет бумаги)', 'Добавить бумагу'),
    ('*', 809, 'inputMediaChangeRequest', 'Требуется смена бумаги', None),
    ('*', 810, 'inputManualInputRequest', 'Требуется ручная подача', None),
    ('*', 811, 'inputTrayPositionFailure', 'Ошибка позиционирования лотка', None),
    ('*', 812, 'inputTrayElevationFailure', 'Ошибка подъёма лотка', None),
    ('*', 813, 'inputCannotFeedSizeSelected', 'Невозможно подать выбранный размер', None),
    ('*', 814, 'inputMediaTrayFeedError', 'Ошибка подачи из лотка', None),
    ('*', 815, 'inputMediaTrayJam', 'Замятие в лотке', 'Устранить замятие'),
    ('*', 816, 'inputMediaTrayFailure', 'Неисправность лотка', None),
    ('*', 817, 'inputMediaTrayPickRollerLifeWarn', 'Ролик подачи: ресурс на исходе', None),
    ('*', 818, 'inputMediaTrayPickRollerLifeOver', 'Ролик подачи: ресурс исчерпан', 'Заменить ролик'),
    ('*', 819, 'inputMediaTrayPickRollerFailure', 'Отказ ролика подачи', None),
    ('*', 820, 'inputMediaTrayPickRollerMissing', 'Ролик подачи отсутствует', None),
    # --- выход (901-907) ---
    ('*', 901, 'outputMediaTrayMissing', 'Выходной лоток отсутствует', None),
    ('*', 902, 'outputMediaTrayAlmostFull', 'Выходной лоток почти полон', None),
    ('*', 903, 'outputMediaTrayFull', 'Выходной лоток полон', 'Освободить лоток'),
    ('*', 904, 'outputMailboxSelectFailure', 'Ошибка выбора ящика', None),
    ('*', 905, 'outputMediaTrayFeedError', 'Ошибка подачи на выход', None),
    ('*', 906, 'outputMediaTrayJam', 'Замятие на выходе', 'Устранить замятие'),
    ('*', 907, 'outputMediaTrayFailure', 'Неисправность выходного лотка', None),
    # --- маркер/фьюзер (1001-1030) ---
    ('*', 1001, 'markerFuserUnderTemperature', 'Фьюзер: недогрев', None),
    ('*', 1002, 'markerFuserOverTemperature', 'Фьюзер: перегрев', None),
    ('*', 1003, 'markerFuserTimingFailure', 'Фьюзер: сбой синхронизации', None),
    ('*', 1004, 'markerFuserThermistorFailure', 'Фьюзер: отказ термистора', None),
    ('*', 1005, 'markerAdjustingPrintQuality', 'Регулировка качества печати', None),
    ('*', 1010, 'markerLifeAlmostOver', 'Ресурс маркера на исходе', None),
    ('*', 1011, 'markerLifeOver', 'Ресурс маркера исчерпан', None),
    ('*', 1013, 'markerMissing', 'Маркер отсутствует', None),
    ('*', 1014, 'markerMotorFailure', 'Отказ двигателя маркера', None),
    ('*', 1019, 'markerPowerSaver', 'Маркер: спящий режим', None),
    ('*', 1030, 'markerWarmingUp', 'Маркер: прогрев', None),
    # --- расходники (1101-1131) ---
    ('*', 1101, 'markerTonerEmpty', 'Тонер закончился', 'Заменить тонер'),
    ('*', 1102, 'markerInkEmpty', 'Чернила закончились', 'Заменить чернила'),
    ('*', 1103, 'markerPrintRibbonEmpty', 'Лента закончилась', None),
    ('*', 1104, 'markerTonerAlmostEmpty', 'Тонер заканчивается', 'Подготовить картридж'),
    ('*', 1105, 'markerInkAlmostEmpty', 'Чернила заканчиваются', None),
    ('*', 1106, 'markerPrintRibbonAlmostEmpty', 'Лента заканчивается', None),
    ('*', 1107, 'markerWasteTonerReceptacleAlmostFull', 'Бункер отработанного тонера почти полон', None),
    ('*', 1108, 'markerWasteInkReceptacleAlmostFull', 'Бункер отработанных чернил почти полон', None),
    ('*', 1109, 'markerWasteTonerReceptacleFull', 'Бункер отработанного тонера полон', 'Заменить/опустошить бункер'),
    ('*', 1110, 'markerWasteInkReceptacleFull', 'Бункер отработанных чернил полон', None),
    ('*', 1111, 'markerOpcLifeAlmostOver', 'Фотобарабан: ресурс на исходе', None),
    ('*', 1112, 'markerOpcLifeOver', 'Фотобарабан: ресурс исчерпан', 'Заменить фотобарабан'),
    ('*', 1113, 'markerDeveloperAlmostEmpty', 'Девелопер заканчивается', None),
    ('*', 1114, 'markerDeveloperEmpty', 'Девелопер закончился', None),
    ('*', 1115, 'markerTonerCartridgeMissing', 'Картридж с тонером отсутствует', 'Установить картридж'),
    ('*', 1116, 'markerCleanerMissing', 'Чистящий узел отсутствует', None),
    ('*', 1117, 'markerDeveloperMissing', 'Девелопер отсутствует', None),
    ('*', 1118, 'markerFuserMissing', 'Фьюзер отсутствует', None),
    ('*', 1119, 'markerInkMissing', 'Чернила отсутствуют', None),
    ('*', 1120, 'markerOpcMissing', 'Фотобарабан отсутствует', None),
    ('*', 1121, 'markerPrintRibbonMissing', 'Лента отсутствует', None),
    ('*', 1122, 'markerSupplyAlmostEmpty', 'Расходник заканчивается', None),
    ('*', 1123, 'markerSupplyEmpty', 'Расходник закончился', 'Заменить расходник'),
    ('*', 1124, 'markerSupplyMissing', 'Расходник отсутствует', None),
    ('*', 1125, 'markerWasteAlmostFull', 'Бункер отходов почти полон', None),
    ('*', 1126, 'markerWasteFull', 'Бункер отходов полон', None),
    ('*', 1127, 'markerWasteMissing', 'Бункер отходов отсутствует', None),
    ('*', 1128, 'markerWasteInkReceptacleMissing', 'Бункер отработанных чернил отсутствует', None),
    ('*', 1129, 'markerWasteTonerReceptacleMissing', 'Бункер отработанного тонера отсутствует', None),
    ('*', 1130, 'markerTonerMissing', 'Тонер отсутствует', 'Установить картридж'),
    ('*', 1131, 'markerSupplyFailure', 'Сбой расходника', None),
    # --- медиатракт (1301-1334) ---
    ('*', 1301, 'mediaPathMediaTrayMissing', 'Лоток тракта отсутствует', None),
    ('*', 1302, 'mediaPathMediaTrayAlmostFull', 'Лоток тракта почти полон', None),
    ('*', 1303, 'mediaPathMediaTrayFull', 'Лоток тракта полон', None),
    ('*', 1304, 'mediaPathCannotDuplexMediaSelected', 'Дуплекс невозможен для выбранной бумаги', None),
    ('*', 1305, 'mediaPathFailure', 'Неисправность медиатракта', None),
    ('*', 1306, 'mediaPathJam', 'Замятие в медиатракте', 'Устранить замятие'),
    ('*', 1310, 'mediaPathInputRequest', 'Требуется подача бумаги', None),
    ('*', 1311, 'mediaPathInputFeedError', 'Ошибка подачи на входе', None),
    ('*', 1312, 'mediaPathInputJam', 'Замятие на входе', 'Устранить замятие'),
    ('*', 1321, 'mediaPathOutputFeedError', 'Ошибка подачи на выходе', None),
    ('*', 1322, 'mediaPathOutputJam', 'Замятие на выходе', 'Устранить замятие'),
    ('*', 1323, 'mediaPathOutputFull', 'Выход переполнен', None),
    ('*', 1331, 'mediaPathPickRollerLifeWarn', 'Ролик тракта: ресурс на исходе', None),
    ('*', 1332, 'mediaPathPickRollerLifeOver', 'Ролик тракта: ресурс исчерпан', None),
    ('*', 1333, 'mediaPathPickRollerFailure', 'Отказ ролика тракта', None),
    ('*', 1334, 'mediaPathPickRollerMissing', 'Ролик тракта отсутствует', None),
    # --- интерпретатор (1501-1509) ---
    ('*', 1501, 'interpreterMemoryIncrease', 'Память увеличена', None),
    ('*', 1502, 'interpreterMemoryDecrease', 'Память уменьшена', None),
    ('*', 1503, 'interpreterCartridgeAdded', 'Картридж добавлен', None),
    ('*', 1504, 'interpreterCartridgeDeleted', 'Картридж извлечён', None),
    ('*', 1505, 'interpreterResourceAdded', 'Ресурс добавлен', None),
    ('*', 1506, 'interpreterResourceDeleted', 'Ресурс удалён', None),
    ('*', 1507, 'interpreterResourceUnavailable', 'Ресурс недоступен', None),
    ('*', 1509, 'interpreterComplexPageEncountered', 'Слишком сложная страница', None),
    # --- сканер (5101-5114) ---
    ('*', 5101, 'scannerLightLifeAlmostOver', 'Лампа сканера: ресурс на исходе', None),
    ('*', 5102, 'scannerLightLifeOver', 'Лампа сканера: ресурс исчерпан', None),
    ('*', 5103, 'scannerLightFailure', 'Отказ лампы сканера', None),
    ('*', 5104, 'scannerLightMissing', 'Лампа сканера отсутствует', None),
    ('*', 5111, 'scannerSensorLifeAlmostOver', 'Датчик сканера: ресурс на исходе', None),
    ('*', 5112, 'scannerSensorLifeOver', 'Датчик сканера: ресурс исчерпан', None),
    ('*', 5113, 'scannerSensorFailure', 'Отказ датчика сканера', None),
    ('*', 5114, 'scannerSensorMissing', 'Датчик сканера отсутствует', None),
    # --- тракт сканера (5201-5234) ---
    ('*', 5201, 'scanMediaPathTrayMissing', 'Лоток сканера отсутствует', None),
    ('*', 5202, 'scanMediaPathTrayAlmostFull', 'Лоток сканера почти полон', None),
    ('*', 5203, 'scanMediaPathTrayFull', 'Лоток сканера полон', None),
    ('*', 5205, 'scanMediaPathFailure', 'Неисправность тракта сканера', None),
    ('*', 5206, 'scanMediaPathJam', 'Замятие в тракте сканера', 'Устранить замятие'),
    ('*', 5210, 'scanMediaPathInputRequest', 'Требуется подача оригинала', None),
    ('*', 5211, 'scanMediaPathInputFeedError', 'Ошибка подачи оригинала', None),
    ('*', 5212, 'scanMediaPathInputJam', 'Замятие на входе сканера', 'Устранить замятие'),
    ('*', 5221, 'scanMediaPathOutputFeedError', 'Ошибка вывода сканера', None),
    ('*', 5222, 'scanMediaPathOutputJam', 'Замятие на выходе сканера', 'Устранить замятие'),
    ('*', 5223, 'scanMediaPathOutputFull', 'Выход сканера переполнен', None),
    ('*', 5231, 'scanMediaPathPickRollerLifeWarn', 'Ролик сканера: ресурс на исходе', None),
    ('*', 5232, 'scanMediaPathPickRollerLifeOver', 'Ролик сканера: ресурс исчерпан', None),
    ('*', 5233, 'scanMediaPathPickRollerFailure', 'Отказ ролика сканера', None),
    ('*', 5234, 'scanMediaPathPickRollerMissing', 'Ролик сканера отсутствует', None),
    # --- факс-модем (6101-6105) ---
    ('*', 6101, 'faxModemMissing', 'Факс-модем отсутствует', None),
    ('*', 6102, 'faxModemLifeAlmostOver', 'Факс-модем: ресурс на исходе', None),
    ('*', 6103, 'faxModemLifeOver', 'Факс-модем: ресурс исчерпан', None),
    ('*', 6104, 'faxModemTurnedOn', 'Факс-модем включён', None),
    ('*', 6105, 'faxModemTurnedOff', 'Факс-модем выключен', None),
    # --- вендорские уточнения (при необходимости дополнять сюда) ---
    ('kyocera', 1001, 'markerFuserUnderTemperature', 'Фьюзер: недогрев (прогрев/сон)', 'Обычно проходит после прогрева'),
]

ALERT_DB_SCHEMA = """
CREATE TABLE IF NOT EXISTS alert_codes (
    vendor TEXT NOT NULL DEFAULT '*',   -- '*' = общий стандарт RFC 3805
    code INTEGER NOT NULL,
    name TEXT,                          -- powerUp, jam, ...
    title_ru TEXT NOT NULL,             -- расшифровка
    hint_ru TEXT,                       -- что делать (опционально)
    PRIMARY KEY (vendor, code)
);
"""
